name: make CI

on: [push, pull_request]

jobs:
  make-amd64:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup wasmtime
        run: curl https://wasmtime.dev/install.sh -sSf | bash
      - name: Build with make
        run: make
      - name: Run examples with make
        run: make run-examples
